set -g default-terminal "tmux-256color"
set -as terminal-features ',*:RGB'
set -g mouse on
set -s escape-time 0
set -g history-limit 50000

set -g allow-passthrough on
set -g extended-keys on
set -g extended-keys-format csi-u
set -as terminal-features 'xterm*:extkeys'

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
